### ISSUE TITLE
mock fails with super duper symfony 5 process

### ISSUE THREAD

**Issue by haeber** [chubbyphp/chubbyphp-socket-server-mock#3]
Symfony 5 changed the construct of Symfony\Component\Process\Process\Process, the 1st argument is now an array instead of string. This will fail createSocketServerMock, because there is no composer.json restriction that it won't work with symfony 5.

It seems there is already some work in master, but a new release would be outstanding.

**Comment by dominikzogg** [comment]
See, https://github.com/chubbyphp/chubbyphp-socket-server-mock/commit/0603c473b6e89ef5a1bd9f49a74ba202924920ce

But i haven't released it cause its red

**Comment by dominikzogg** [comment]
https://github.com/chubbyphp/chubbyphp-socket-server-mock/commit/f2fa3f45d1fed7535474f9a445b4e09c1b50e7cf

**Comment by dominikzogg** [comment]
https://github.com/chubbyphp/chubbyphp-socket-server-mock/releases/tag/1.1.1

**Comment by haeber** [comment]
Thanks a lot. 👍

**Comment by dominikzogg** [comment]
your welcome
